module.exports = {
    TITLE_KEY: 'title',
    ORIGINAL_TITLE_KEY: 'original_title',
    OVERVIEW_KEY: 'overview',
    POSTER_PATH_KEY: 'poster_path',
    GENRES_KEY: ['genres', 'genre_ids'],
    RUNTIME_KEY: 'runtime',
    RELEASE_DATE_KEY: 'release_date',
    STATUS_KEY: 'status',
    ORIGINAL_LANGUAGE_KEY: 'original_language',
    SPOKEN_LANGUAGES_KEY: 'spoken_languages',
    ADULT_KEY: 'adult',
    VOTE_AVERAGE_KEY: 'vote_average',
    POPULARITY_KEY: 'popularity',
    BUDGET_KEY: 'budget',
    REVENUE_KEY: 'revenue',
    PRODUCTION_COMPANIES_KEY: 'production_companies',
    PRODUCTION_COUNTRIES_KEY: 'production_countries',
    NAME_KEY: 'name',
    ORIGIN_COUNTRY_KEY: 'origin_country',
    ENGLISH_NAME_KEY: 'english_name',
    LOGO_PATH_KEY: 'logo_path',
    ISO_3166_1_KEY: 'iso_3166_1'
}